INSERT INTO quotes (quote, author) VALUES
('The only way to do great work is to love what you do.', 'Steve Jobs'),
('In three words I can sum up everything I''ve learned about life: it goes on.', 'Robert Frost'),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('Get busy living or get busy dying.', 'Stephen King'),
('You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy'),
('The purpose of our lives is to be happy.', 'Dalai Lama'),
('Get busy living, or get busy dying.', 'Stephen King'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('The world is a book and those who do not travel read only one page.', 'St. Augustine'),
('If life were predictable it would cease to be life, and be without flavor.', 'Eleanor Roosevelt'),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith'),
('Life is really simple, but we insist on making it complicated.', 'Confucius'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy'),
('The purpose of our lives is to be happy.', 'Dalai Lama'),
('Get busy living, or get busy dying.', 'Stephen King'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('The world is a book and those who do not travel read only one page.', 'St. Augustine'),
('If life were predictable it would cease to be life, and be without flavor.', 'Eleanor Roosevelt'),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith'),
('Life is really simple, but we insist on making it complicated.', 'Confucius'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy'),
('The purpose of our lives is to be happy.', 'Dalai Lama'),
('Get busy living, or get busy dying.', 'Stephen King'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('The world is a book and those who do not travel read only one page.', 'St. Augustine'),
('If life were predictable it would cease to be life, and be without flavor.', 'Eleanor Roosevelt'),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith'),
('Life is really simple, but we insist on making it complicated.', 'Confucius'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy'),
('The purpose of our lives is to be happy.', 'Dalai Lama'),
('Get busy living, or get busy dying.', 'Stephen King'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('The world is a book and those who do not travel read only one page.', 'St. Augustine'),
('If life were predictable it would cease to be life, and be without flavor.', 'Eleanor Roosevelt'),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith'),
('Life is really simple, but we insist on making it complicated.', 'Confucius'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy'),
('The purpose of our lives is to be happy.', 'Dalai Lama'),
('Get busy living, or get busy dying.', 'Stephen King'),
('Life is what happens when you''re busy making other plans.', 'John Lennon'),
('The world is a book and those who do not travel read only one page.', 'St. Augustine'),
('If life were predictable it would cease to be life, and be without flavor.', 'Eleanor Roosevelt'),
('Life is a journey that must be traveled no matter how bad the roads and accommodations.', 'Oliver Goldsmith'),
('Life is really simple, but we insist on making it complicated.', 'Confucius');